apiVersion: apps/v1
kind: Deployment
metadata:
  name: must-gather-operator
  namespace: openshift-must-gather-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: must-gather-operator
  template:
    metadata:
      labels:
        name: must-gather-operator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
      serviceAccountName: must-gather-operator
      containers:
        - name: must-gather-operator
          image: quay.io/redhat-user-workloads/rhn-support-bpratt-tenant/must-gather-operator/operator@sha256:2865ce83e65278d96098ccc40ad35af29f500baf79411a7b8ad5f862d68f7e7a
          command:
          - must-gather-operator
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "must-gather-operator"
